xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: [ "http://localhost:9200" ]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "elastic"

pipeline.batch.size: 125
pipeline.batch.delay: 50
pipeline.workers: 4

queue.type: persisted
queue.max_bytes: 1024mb
