- pipeline.id: auditing
  path.config: "/usr/share/logstash/pipeline/auditing.conf"
  
- pipeline.id: logs
  path.config: "/usr/share/logstash/pipeline/logs.conf"
  
- pipeline.id: mobile
  path.config: "/usr/share/logstash/pipeline/mobile.conf"
  
- pipeline.id: log4j
  path.config: "/usr/share/logstash/pipeline/log4j.conf"
